CNN updates
shanest/neural-vision-most pull request #2
Opened 2018-06-14 09:04 UTC by LewisOs

Hi Shane,

Here are the CNN updates. I've a strong suspicion that I'm not using the loops properly in the nested loop section, but otherwise I think the rest is alright... Hope it looks okay to you.

Cheers, Lewis.

2018-06-14 09:08 UTC, shanest commented on models.py
> +        for conv in range(layer["num_convs"]):
Two small comments, one very pedantic and one somewhat more interesting.

(i) Could you use single quotes / apostrophes when accessing dictionary fields (e.g. `params['layers']` and `layer['num_convs']`?  It doesn't matter to a huge degree, but the consistency with how I've been doing it suits my aesthetic sensibility :-).

(ii) I would also write the nested loop as `for _ in range(layer['num_convs'])`.  Currently, you're assigning to `conv` the integer values in the `range`; but notice that you never use that variable `conv`.  Using the underscore `_` allows you to run the loop without assigning any variables that then don't get used.

2018-06-14 09:10 UTC, shanest commented on models.py
> +    for layer in params["dense"]:
See earlier comment on single quotes :-)

2018-06-14 09:13 UTC, shanest requested changes
Hi Lewis,

The code looks great!  I'm requesting a few changes before merging the pull request, largely just to exhibit the mechanics of a code review :-).  You should see some comments on the files in this pull request.

There are two other changes that I'd request:

(1) You should add "and Lewis O'Sullivan" to the copyright statement at the top of the files you've worked on :-).

(2) Can you delete the non-Python files from the repository? (e.g. .DS_Store, __pycache__, images/.DS_Store). You can delete them from the web interface for GitHub; then, in the future when using the Desktop app, you can just make sure that they are unchecked when you make a commit.

Cheers!

2018-06-18 09:41 UTC, LewisOs commented
Hi Shane,

I've done the edits you requested. Hope it all looks okay.

Ta, Lewis.

2018-06-18 09:46 UTC, shanest commented on models.py
> +                    inputs = ,
`inputs` should be `locs`, which is of shape `[batch_size, 2]`

2018-06-18 09:49 UTC, shanest commented
Hi Lewis,

Code looks great!  And well done getting on the glimpse_network too!

Two very, very minor things before I finally pull :-):

* inputs should be `locs` to that layer of the glimpse network you were wondering about

* Somehow this update added some Spyder files and a directory "NNs for most" to the repository.  Can you delete those?  (Remember to always check which files are checked as being committed in the Desktop app.)

Once these little things are done, I'll pull it in to the main repo!

2018-06-18 10:24 UTC, LewisOs commented
Hi again -  I think all the extra files are gone now. I'll send another pull request when I'm done working on the glimpse network.

Cheers, Lewis.

2018-06-18 10:28 UTC, shanest approved these changes

2018-06-18 10:29 UTC, merged

2018-06-18 10:29 UTC, shanest commented
Awesome, I just merged into the main repo.  Congrats on your first successful pull request!!